[package]
name = "aurora"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dynamic_shaders= []

#[[example]]
#name = "window"
#required-features = ["dynamic_shaders"]

[dependencies]
cfg-if = "1"
winit = "0.30.9"
log  = "0.4.25"
wgpu = "24.0.1"
glam = "0.30.0"
eframe = "0.31.0"
egui = "0.31.0"
egui-wgpu = "0.31.0"
pollster = "0.4.0"
egui-winit = "0.31.0"
